// Code generated by hertz generator.

package report

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	report "sfw/biz/model/api/report"
)

// Report .
// @router /api/v1/report [POST]
func Report(ctx context.Context, c *app.RequestContext) {
	var err error
	var req report.ReportReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(report.ReportResp)

	c.JSON(consts.StatusOK, resp)
}

// AdminReportList .
// @router /api/v1/admin/report/list [GET]
func AdminReportList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req report.AdminReportListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(report.AdminReportListResp)

	c.JSON(consts.StatusOK, resp)
}

// AdminReportHandle .
// @router /api/v1/admin/report/handle [POST]
func AdminReportHandle(ctx context.Context, c *app.RequestContext) {
	var err error
	var req report.AdminReportHandleReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(report.AdminReportHandleResp)

	c.JSON(consts.StatusOK, resp)
}

// AdminVideoList .
// @router /api/v1/admin/video/list [GET]
func AdminVideoList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req report.AdminVideoListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(report.AdminVideoListResp)

	c.JSON(consts.StatusOK, resp)
}

// AdminVideoHandle .
// @router /api/v1/admin/video/handle [POST]
func AdminVideoHandle(ctx context.Context, c *app.RequestContext) {
	var err error
	var req report.AdminVideoHandleReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(report.AdminVideoHandleResp)

	c.JSON(consts.StatusOK, resp)
}
