// Code generated by hertz generator.

package report

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reportMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _report0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminreporthandleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminreportlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminvideohandleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminvideolistMw() []app.HandlerFunc {
	// your code...
	return nil
}
