// Code generated by hertz generator.

package main

import (
	webs "sfw/biz/router/websocket"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	Initialize()

	h := server.Default()
	InstallSentinel(h)

	ws := server.Default(server.WithHostPorts(`:10001`))
	ws.NoHijackConnPool = true

	register(h)
	webs.WebsocketRegister(ws)

	go ws.Spin()
	h.Spin()
}
