// Code generated by hertz generator.

package oss

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ossMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _osscallbackmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _callbackMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _osscallbackavatarmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _osscallbackfopmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}
