// Code generated by hertz generator.

package oss

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	oss "sfw/biz/model/api/oss"
)

// OssCallbackMethod .
// @router /api/v1/oss/callback [POST]
func OssCallbackMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req oss.OssCallbackReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(oss.OssCallbackResp)

	c.JSON(consts.StatusOK, resp)
}
