// Code generated by hertz generator.

package activity

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	activity "sfw/biz/model/api/activity"
)

// ActivityInfoMethod .
// @router /api/v1/activity/info [GET]
func ActivityInfoMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req activity.ActivityInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(activity.ActivityInfoResp)

	c.JSON(consts.StatusOK, resp)
}

// ActivityFeedMethod .
// @router /api/v1/activity/feed [GET]
func ActivityFeedMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req activity.ActivityFeedReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(activity.ActivityFeedResp)

	c.JSON(consts.StatusOK, resp)
}

// ActivityPublishMethod .
// @router /api/v1/activity/publish [POST]
func ActivityPublishMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req activity.ActivityPublishReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(activity.ActivityPublishResp)

	c.JSON(consts.StatusOK, resp)
}

// ActivityListMethod .
// @router /api/v1/activity/list [GET]
func ActivityListMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req activity.ActivityListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(activity.ActivityListResp)

	c.JSON(consts.StatusOK, resp)
}
