// Code generated by hertz generator.

package activity

import (
	"context"

	activity "sfw/biz/model/api/activity"
	"sfw/biz/service"
	"sfw/pkg/errno"
	"sfw/pkg/utils"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// ActivityInfoMethod .
// @router /api/v1/activity/info [GET]
func ActivityInfoMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req activity.ActivityInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(activity.ActivityInfoResp)

	c.JSON(consts.StatusOK, resp)
}

// ActivityFeedMethod .
// @router /api/v1/activity/feed [GET]
func ActivityFeedMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req activity.ActivityFeedReq
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := utils.CreateBaseHttpResponse(err)
		c.JSON(consts.StatusOK, activity.ActivityFeedResp{
			Code: resp.Code,
			Msg:  resp.Msg,
		})
		return
	}

	resp, err := service.NewActivityService(ctx, c).NewFeedEvent(&req)
	if err != nil {
		resp := utils.CreateBaseHttpResponse(err)
		c.JSON(consts.StatusOK, activity.ActivityFeedResp{
			Code: resp.Code,
			Msg:  resp.Msg,
		})
		return
	}

	c.JSON(consts.StatusOK, activity.ActivityFeedResp{
		Code: errno.NoError.Code,
		Msg:  errno.NoError.Message,
		Data: resp,
	})
}

// ActivityPublishMethod .
// @router /api/v1/activity/publish [POST]
func ActivityPublishMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req activity.ActivityPublishReq
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := utils.CreateBaseHttpResponse(err)
		c.JSON(consts.StatusOK, activity.ActivityPublishResp{
			Code: resp.Code,
			Msg:  resp.Msg,
		})
		return
	}

	err = service.NewActivityService(ctx, c).NewPublishEvent(&req)
	if err != nil {
		resp := utils.CreateBaseHttpResponse(err)
		c.JSON(consts.StatusOK, activity.ActivityPublishResp{
			Code: resp.Code,
			Msg:  resp.Msg,
		})
		return
	}

	c.JSON(consts.StatusOK, activity.ActivityPublishResp{
		Code: errno.NoError.Code,
		Msg:  errno.NoError.Message,
	})
}

// ActivityListMethod .
// @router /api/v1/activity/list [GET]
func ActivityListMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req activity.ActivityListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := utils.CreateBaseHttpResponse(err)
		c.JSON(consts.StatusOK, activity.ActivityListResp{
			Code: resp.Code,
			Msg:  resp.Msg,
		})
		return
	}

	resp, err := service.NewActivityService(ctx, c).NewListEvent(&req)
	if err != nil {
		resp := utils.CreateBaseHttpResponse(err)
		c.JSON(consts.StatusOK, activity.ActivityListResp{
			Code: resp.Code,
			Msg:  resp.Msg,
		})
		return
	}

	c.JSON(consts.StatusOK, activity.ActivityListResp{
		Code: errno.NoError.Code,
		Msg:  errno.NoError.Message,
		Data: resp,
	})
}
