// Code generated by hertz generator.

package video

import (
	auth "sfw/biz/router/api/api_auth"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videocategoriesmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videofeedmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videoinfomethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videolistmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videopopularmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videopublishmethodMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _videosearchmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _videosubmitallmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videosubmitlockedmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videosubmitpassedmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videosubmitreviewmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _coverMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videocoveruploadmethodMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _customMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videocustomfeedmethodMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}
