// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"sfw/biz/dal/model"
)

func newActivityReport(db *gorm.DB, opts ...gen.DOOption) activityReport {
	_activityReport := activityReport{}

	_activityReport.activityReportDo.UseDB(db, opts...)
	_activityReport.activityReportDo.UseModel(&model.ActivityReport{})

	tableName := _activityReport.activityReportDo.TableName()
	_activityReport.ALL = field.NewAsterisk(tableName)
	_activityReport.ID = field.NewInt64(tableName, "id")
	_activityReport.UserID = field.NewInt64(tableName, "user_id")
	_activityReport.ActivityID = field.NewInt64(tableName, "activity_id")
	_activityReport.Reason = field.NewString(tableName, "reason")
	_activityReport.CreatedAt = field.NewInt64(tableName, "created_at")
	_activityReport.Status = field.NewString(tableName, "status")
	_activityReport.ResolvedAt = field.NewInt64(tableName, "resolved_at")
	_activityReport.AdminID = field.NewInt64(tableName, "admin_id")

	_activityReport.fillFieldMap()

	return _activityReport
}

// activityReport 动态举报表
type activityReport struct {
	activityReportDo activityReportDo

	ALL        field.Asterisk
	ID         field.Int64  // 举报ID
	UserID     field.Int64  // 用户ID
	ActivityID field.Int64  // 动态ID
	Reason     field.String // 举报原因
	CreatedAt  field.Int64  // 创建时间
	Status     field.String // 举报状态
	ResolvedAt field.Int64  // 解决时间
	AdminID    field.Int64  // 管理员ID

	fieldMap map[string]field.Expr
}

func (a activityReport) Table(newTableName string) *activityReport {
	a.activityReportDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a activityReport) As(alias string) *activityReport {
	a.activityReportDo.DO = *(a.activityReportDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *activityReport) updateTableName(table string) *activityReport {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.UserID = field.NewInt64(table, "user_id")
	a.ActivityID = field.NewInt64(table, "activity_id")
	a.Reason = field.NewString(table, "reason")
	a.CreatedAt = field.NewInt64(table, "created_at")
	a.Status = field.NewString(table, "status")
	a.ResolvedAt = field.NewInt64(table, "resolved_at")
	a.AdminID = field.NewInt64(table, "admin_id")

	a.fillFieldMap()

	return a
}

func (a *activityReport) WithContext(ctx context.Context) *activityReportDo {
	return a.activityReportDo.WithContext(ctx)
}

func (a activityReport) TableName() string { return a.activityReportDo.TableName() }

func (a activityReport) Alias() string { return a.activityReportDo.Alias() }

func (a activityReport) Columns(cols ...field.Expr) gen.Columns {
	return a.activityReportDo.Columns(cols...)
}

func (a *activityReport) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *activityReport) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 8)
	a.fieldMap["id"] = a.ID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["activity_id"] = a.ActivityID
	a.fieldMap["reason"] = a.Reason
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["status"] = a.Status
	a.fieldMap["resolved_at"] = a.ResolvedAt
	a.fieldMap["admin_id"] = a.AdminID
}

func (a activityReport) clone(db *gorm.DB) activityReport {
	a.activityReportDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a activityReport) replaceDB(db *gorm.DB) activityReport {
	a.activityReportDo.ReplaceDB(db)
	return a
}

type activityReportDo struct{ gen.DO }

func (a activityReportDo) Debug() *activityReportDo {
	return a.withDO(a.DO.Debug())
}

func (a activityReportDo) WithContext(ctx context.Context) *activityReportDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a activityReportDo) ReadDB() *activityReportDo {
	return a.Clauses(dbresolver.Read)
}

func (a activityReportDo) WriteDB() *activityReportDo {
	return a.Clauses(dbresolver.Write)
}

func (a activityReportDo) Session(config *gorm.Session) *activityReportDo {
	return a.withDO(a.DO.Session(config))
}

func (a activityReportDo) Clauses(conds ...clause.Expression) *activityReportDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a activityReportDo) Returning(value interface{}, columns ...string) *activityReportDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a activityReportDo) Not(conds ...gen.Condition) *activityReportDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a activityReportDo) Or(conds ...gen.Condition) *activityReportDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a activityReportDo) Select(conds ...field.Expr) *activityReportDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a activityReportDo) Where(conds ...gen.Condition) *activityReportDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a activityReportDo) Order(conds ...field.Expr) *activityReportDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a activityReportDo) Distinct(cols ...field.Expr) *activityReportDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a activityReportDo) Omit(cols ...field.Expr) *activityReportDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a activityReportDo) Join(table schema.Tabler, on ...field.Expr) *activityReportDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a activityReportDo) LeftJoin(table schema.Tabler, on ...field.Expr) *activityReportDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a activityReportDo) RightJoin(table schema.Tabler, on ...field.Expr) *activityReportDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a activityReportDo) Group(cols ...field.Expr) *activityReportDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a activityReportDo) Having(conds ...gen.Condition) *activityReportDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a activityReportDo) Limit(limit int) *activityReportDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a activityReportDo) Offset(offset int) *activityReportDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a activityReportDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *activityReportDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a activityReportDo) Unscoped() *activityReportDo {
	return a.withDO(a.DO.Unscoped())
}

func (a activityReportDo) Create(values ...*model.ActivityReport) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a activityReportDo) CreateInBatches(values []*model.ActivityReport, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a activityReportDo) Save(values ...*model.ActivityReport) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a activityReportDo) First() (*model.ActivityReport, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActivityReport), nil
	}
}

func (a activityReportDo) Take() (*model.ActivityReport, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActivityReport), nil
	}
}

func (a activityReportDo) Last() (*model.ActivityReport, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActivityReport), nil
	}
}

func (a activityReportDo) Find() ([]*model.ActivityReport, error) {
	result, err := a.DO.Find()
	return result.([]*model.ActivityReport), err
}

func (a activityReportDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ActivityReport, err error) {
	buf := make([]*model.ActivityReport, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a activityReportDo) FindInBatches(result *[]*model.ActivityReport, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a activityReportDo) Attrs(attrs ...field.AssignExpr) *activityReportDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a activityReportDo) Assign(attrs ...field.AssignExpr) *activityReportDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a activityReportDo) Joins(fields ...field.RelationField) *activityReportDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a activityReportDo) Preload(fields ...field.RelationField) *activityReportDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a activityReportDo) FirstOrInit() (*model.ActivityReport, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActivityReport), nil
	}
}

func (a activityReportDo) FirstOrCreate() (*model.ActivityReport, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActivityReport), nil
	}
}

func (a activityReportDo) FindByPage(offset int, limit int) (result []*model.ActivityReport, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a activityReportDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a activityReportDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a activityReportDo) Delete(models ...*model.ActivityReport) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *activityReportDo) withDO(do gen.Dao) *activityReportDo {
	a.DO = *do.(*gen.DO)
	return a
}
