// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"sfw/biz/dal/model"
)

func newActivityImage(db *gorm.DB, opts ...gen.DOOption) activityImage {
	_activityImage := activityImage{}

	_activityImage.activityImageDo.UseDB(db, opts...)
	_activityImage.activityImageDo.UseModel(&model.ActivityImage{})

	tableName := _activityImage.activityImageDo.TableName()
	_activityImage.ALL = field.NewAsterisk(tableName)
	_activityImage.ImageID = field.NewInt64(tableName, "image_id")
	_activityImage.ActivityID = field.NewInt64(tableName, "activity_id")
	_activityImage.CreatedAt = field.NewInt64(tableName, "created_at")
	_activityImage.DeletedAt = field.NewInt64(tableName, "deleted_at")

	_activityImage.fillFieldMap()

	return _activityImage
}

// activityImage 图片表
type activityImage struct {
	activityImageDo activityImageDo

	ALL        field.Asterisk
	ImageID    field.Int64 // 图片ID
	ActivityID field.Int64 // 动态ID
	CreatedAt  field.Int64 // 创建时间
	DeletedAt  field.Int64 // 删除时间

	fieldMap map[string]field.Expr
}

func (a activityImage) Table(newTableName string) *activityImage {
	a.activityImageDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a activityImage) As(alias string) *activityImage {
	a.activityImageDo.DO = *(a.activityImageDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *activityImage) updateTableName(table string) *activityImage {
	a.ALL = field.NewAsterisk(table)
	a.ImageID = field.NewInt64(table, "image_id")
	a.ActivityID = field.NewInt64(table, "activity_id")
	a.CreatedAt = field.NewInt64(table, "created_at")
	a.DeletedAt = field.NewInt64(table, "deleted_at")

	a.fillFieldMap()

	return a
}

func (a *activityImage) WithContext(ctx context.Context) *activityImageDo {
	return a.activityImageDo.WithContext(ctx)
}

func (a activityImage) TableName() string { return a.activityImageDo.TableName() }

func (a activityImage) Alias() string { return a.activityImageDo.Alias() }

func (a activityImage) Columns(cols ...field.Expr) gen.Columns {
	return a.activityImageDo.Columns(cols...)
}

func (a *activityImage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *activityImage) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 4)
	a.fieldMap["image_id"] = a.ImageID
	a.fieldMap["activity_id"] = a.ActivityID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
}

func (a activityImage) clone(db *gorm.DB) activityImage {
	a.activityImageDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a activityImage) replaceDB(db *gorm.DB) activityImage {
	a.activityImageDo.ReplaceDB(db)
	return a
}

type activityImageDo struct{ gen.DO }

func (a activityImageDo) Debug() *activityImageDo {
	return a.withDO(a.DO.Debug())
}

func (a activityImageDo) WithContext(ctx context.Context) *activityImageDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a activityImageDo) ReadDB() *activityImageDo {
	return a.Clauses(dbresolver.Read)
}

func (a activityImageDo) WriteDB() *activityImageDo {
	return a.Clauses(dbresolver.Write)
}

func (a activityImageDo) Session(config *gorm.Session) *activityImageDo {
	return a.withDO(a.DO.Session(config))
}

func (a activityImageDo) Clauses(conds ...clause.Expression) *activityImageDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a activityImageDo) Returning(value interface{}, columns ...string) *activityImageDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a activityImageDo) Not(conds ...gen.Condition) *activityImageDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a activityImageDo) Or(conds ...gen.Condition) *activityImageDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a activityImageDo) Select(conds ...field.Expr) *activityImageDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a activityImageDo) Where(conds ...gen.Condition) *activityImageDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a activityImageDo) Order(conds ...field.Expr) *activityImageDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a activityImageDo) Distinct(cols ...field.Expr) *activityImageDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a activityImageDo) Omit(cols ...field.Expr) *activityImageDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a activityImageDo) Join(table schema.Tabler, on ...field.Expr) *activityImageDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a activityImageDo) LeftJoin(table schema.Tabler, on ...field.Expr) *activityImageDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a activityImageDo) RightJoin(table schema.Tabler, on ...field.Expr) *activityImageDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a activityImageDo) Group(cols ...field.Expr) *activityImageDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a activityImageDo) Having(conds ...gen.Condition) *activityImageDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a activityImageDo) Limit(limit int) *activityImageDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a activityImageDo) Offset(offset int) *activityImageDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a activityImageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *activityImageDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a activityImageDo) Unscoped() *activityImageDo {
	return a.withDO(a.DO.Unscoped())
}

func (a activityImageDo) Create(values ...*model.ActivityImage) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a activityImageDo) CreateInBatches(values []*model.ActivityImage, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a activityImageDo) Save(values ...*model.ActivityImage) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a activityImageDo) First() (*model.ActivityImage, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActivityImage), nil
	}
}

func (a activityImageDo) Take() (*model.ActivityImage, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActivityImage), nil
	}
}

func (a activityImageDo) Last() (*model.ActivityImage, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActivityImage), nil
	}
}

func (a activityImageDo) Find() ([]*model.ActivityImage, error) {
	result, err := a.DO.Find()
	return result.([]*model.ActivityImage), err
}

func (a activityImageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ActivityImage, err error) {
	buf := make([]*model.ActivityImage, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a activityImageDo) FindInBatches(result *[]*model.ActivityImage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a activityImageDo) Attrs(attrs ...field.AssignExpr) *activityImageDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a activityImageDo) Assign(attrs ...field.AssignExpr) *activityImageDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a activityImageDo) Joins(fields ...field.RelationField) *activityImageDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a activityImageDo) Preload(fields ...field.RelationField) *activityImageDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a activityImageDo) FirstOrInit() (*model.ActivityImage, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActivityImage), nil
	}
}

func (a activityImageDo) FirstOrCreate() (*model.ActivityImage, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActivityImage), nil
	}
}

func (a activityImageDo) FindByPage(offset int, limit int) (result []*model.ActivityImage, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a activityImageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a activityImageDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a activityImageDo) Delete(models ...*model.ActivityImage) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *activityImageDo) withDO(do gen.Dao) *activityImageDo {
	a.DO = *do.(*gen.DO)
	return a
}
