// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"sfw/biz/dal/model"
)

func newActivityLike(db *gorm.DB, opts ...gen.DOOption) activityLike {
	_activityLike := activityLike{}

	_activityLike.activityLikeDo.UseDB(db, opts...)
	_activityLike.activityLikeDo.UseModel(&model.ActivityLike{})

	tableName := _activityLike.activityLikeDo.TableName()
	_activityLike.ALL = field.NewAsterisk(tableName)
	_activityLike.UserID = field.NewInt64(tableName, "user_id")
	_activityLike.ActivityID = field.NewInt64(tableName, "activity_id")
	_activityLike.CreatedAt = field.NewInt64(tableName, "created_at")
	_activityLike.DeletedAt = field.NewInt64(tableName, "deleted_at")

	_activityLike.fillFieldMap()

	return _activityLike
}

// activityLike 动态点赞表
type activityLike struct {
	activityLikeDo activityLikeDo

	ALL        field.Asterisk
	UserID     field.Int64 // 用户ID
	ActivityID field.Int64 // 动态ID
	CreatedAt  field.Int64 // 创建时间
	DeletedAt  field.Int64 // 删除时间

	fieldMap map[string]field.Expr
}

func (a activityLike) Table(newTableName string) *activityLike {
	a.activityLikeDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a activityLike) As(alias string) *activityLike {
	a.activityLikeDo.DO = *(a.activityLikeDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *activityLike) updateTableName(table string) *activityLike {
	a.ALL = field.NewAsterisk(table)
	a.UserID = field.NewInt64(table, "user_id")
	a.ActivityID = field.NewInt64(table, "activity_id")
	a.CreatedAt = field.NewInt64(table, "created_at")
	a.DeletedAt = field.NewInt64(table, "deleted_at")

	a.fillFieldMap()

	return a
}

func (a *activityLike) WithContext(ctx context.Context) *activityLikeDo {
	return a.activityLikeDo.WithContext(ctx)
}

func (a activityLike) TableName() string { return a.activityLikeDo.TableName() }

func (a activityLike) Alias() string { return a.activityLikeDo.Alias() }

func (a activityLike) Columns(cols ...field.Expr) gen.Columns {
	return a.activityLikeDo.Columns(cols...)
}

func (a *activityLike) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *activityLike) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 4)
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["activity_id"] = a.ActivityID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
}

func (a activityLike) clone(db *gorm.DB) activityLike {
	a.activityLikeDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a activityLike) replaceDB(db *gorm.DB) activityLike {
	a.activityLikeDo.ReplaceDB(db)
	return a
}

type activityLikeDo struct{ gen.DO }

func (a activityLikeDo) Debug() *activityLikeDo {
	return a.withDO(a.DO.Debug())
}

func (a activityLikeDo) WithContext(ctx context.Context) *activityLikeDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a activityLikeDo) ReadDB() *activityLikeDo {
	return a.Clauses(dbresolver.Read)
}

func (a activityLikeDo) WriteDB() *activityLikeDo {
	return a.Clauses(dbresolver.Write)
}

func (a activityLikeDo) Session(config *gorm.Session) *activityLikeDo {
	return a.withDO(a.DO.Session(config))
}

func (a activityLikeDo) Clauses(conds ...clause.Expression) *activityLikeDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a activityLikeDo) Returning(value interface{}, columns ...string) *activityLikeDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a activityLikeDo) Not(conds ...gen.Condition) *activityLikeDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a activityLikeDo) Or(conds ...gen.Condition) *activityLikeDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a activityLikeDo) Select(conds ...field.Expr) *activityLikeDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a activityLikeDo) Where(conds ...gen.Condition) *activityLikeDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a activityLikeDo) Order(conds ...field.Expr) *activityLikeDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a activityLikeDo) Distinct(cols ...field.Expr) *activityLikeDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a activityLikeDo) Omit(cols ...field.Expr) *activityLikeDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a activityLikeDo) Join(table schema.Tabler, on ...field.Expr) *activityLikeDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a activityLikeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *activityLikeDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a activityLikeDo) RightJoin(table schema.Tabler, on ...field.Expr) *activityLikeDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a activityLikeDo) Group(cols ...field.Expr) *activityLikeDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a activityLikeDo) Having(conds ...gen.Condition) *activityLikeDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a activityLikeDo) Limit(limit int) *activityLikeDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a activityLikeDo) Offset(offset int) *activityLikeDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a activityLikeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *activityLikeDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a activityLikeDo) Unscoped() *activityLikeDo {
	return a.withDO(a.DO.Unscoped())
}

func (a activityLikeDo) Create(values ...*model.ActivityLike) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a activityLikeDo) CreateInBatches(values []*model.ActivityLike, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a activityLikeDo) Save(values ...*model.ActivityLike) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a activityLikeDo) First() (*model.ActivityLike, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActivityLike), nil
	}
}

func (a activityLikeDo) Take() (*model.ActivityLike, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActivityLike), nil
	}
}

func (a activityLikeDo) Last() (*model.ActivityLike, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActivityLike), nil
	}
}

func (a activityLikeDo) Find() ([]*model.ActivityLike, error) {
	result, err := a.DO.Find()
	return result.([]*model.ActivityLike), err
}

func (a activityLikeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ActivityLike, err error) {
	buf := make([]*model.ActivityLike, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a activityLikeDo) FindInBatches(result *[]*model.ActivityLike, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a activityLikeDo) Attrs(attrs ...field.AssignExpr) *activityLikeDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a activityLikeDo) Assign(attrs ...field.AssignExpr) *activityLikeDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a activityLikeDo) Joins(fields ...field.RelationField) *activityLikeDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a activityLikeDo) Preload(fields ...field.RelationField) *activityLikeDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a activityLikeDo) FirstOrInit() (*model.ActivityLike, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActivityLike), nil
	}
}

func (a activityLikeDo) FirstOrCreate() (*model.ActivityLike, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActivityLike), nil
	}
}

func (a activityLikeDo) FindByPage(offset int, limit int) (result []*model.ActivityLike, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a activityLikeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a activityLikeDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a activityLikeDo) Delete(models ...*model.ActivityLike) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *activityLikeDo) withDO(do gen.Dao) *activityLikeDo {
	a.DO = *do.(*gen.DO)
	return a
}
