// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"sfw/biz/dal/model"
)

func newVideoLabel(db *gorm.DB, opts ...gen.DOOption) videoLabel {
	_videoLabel := videoLabel{}

	_videoLabel.videoLabelDo.UseDB(db, opts...)
	_videoLabel.videoLabelDo.UseModel(&model.VideoLabel{})

	tableName := _videoLabel.videoLabelDo.TableName()
	_videoLabel.ALL = field.NewAsterisk(tableName)
	_videoLabel.VideoID = field.NewInt64(tableName, "video_id")
	_videoLabel.LabelName = field.NewString(tableName, "label_name")
	_videoLabel.CreatedAt = field.NewInt64(tableName, "created_at")
	_videoLabel.DeletedAt = field.NewInt64(tableName, "deleted_at")

	_videoLabel.fillFieldMap()

	return _videoLabel
}

// videoLabel 视频标签关联表
type videoLabel struct {
	videoLabelDo videoLabelDo

	ALL       field.Asterisk
	VideoID   field.Int64  // 视频ID
	LabelName field.String // 标签ID
	CreatedAt field.Int64  // 创建时间
	DeletedAt field.Int64  // 删除时间

	fieldMap map[string]field.Expr
}

func (v videoLabel) Table(newTableName string) *videoLabel {
	v.videoLabelDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v videoLabel) As(alias string) *videoLabel {
	v.videoLabelDo.DO = *(v.videoLabelDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *videoLabel) updateTableName(table string) *videoLabel {
	v.ALL = field.NewAsterisk(table)
	v.VideoID = field.NewInt64(table, "video_id")
	v.LabelName = field.NewString(table, "label_name")
	v.CreatedAt = field.NewInt64(table, "created_at")
	v.DeletedAt = field.NewInt64(table, "deleted_at")

	v.fillFieldMap()

	return v
}

func (v *videoLabel) WithContext(ctx context.Context) *videoLabelDo {
	return v.videoLabelDo.WithContext(ctx)
}

func (v videoLabel) TableName() string { return v.videoLabelDo.TableName() }

func (v videoLabel) Alias() string { return v.videoLabelDo.Alias() }

func (v videoLabel) Columns(cols ...field.Expr) gen.Columns { return v.videoLabelDo.Columns(cols...) }

func (v *videoLabel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *videoLabel) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 4)
	v.fieldMap["video_id"] = v.VideoID
	v.fieldMap["label_name"] = v.LabelName
	v.fieldMap["created_at"] = v.CreatedAt
	v.fieldMap["deleted_at"] = v.DeletedAt
}

func (v videoLabel) clone(db *gorm.DB) videoLabel {
	v.videoLabelDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v videoLabel) replaceDB(db *gorm.DB) videoLabel {
	v.videoLabelDo.ReplaceDB(db)
	return v
}

type videoLabelDo struct{ gen.DO }

func (v videoLabelDo) Debug() *videoLabelDo {
	return v.withDO(v.DO.Debug())
}

func (v videoLabelDo) WithContext(ctx context.Context) *videoLabelDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v videoLabelDo) ReadDB() *videoLabelDo {
	return v.Clauses(dbresolver.Read)
}

func (v videoLabelDo) WriteDB() *videoLabelDo {
	return v.Clauses(dbresolver.Write)
}

func (v videoLabelDo) Session(config *gorm.Session) *videoLabelDo {
	return v.withDO(v.DO.Session(config))
}

func (v videoLabelDo) Clauses(conds ...clause.Expression) *videoLabelDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v videoLabelDo) Returning(value interface{}, columns ...string) *videoLabelDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v videoLabelDo) Not(conds ...gen.Condition) *videoLabelDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v videoLabelDo) Or(conds ...gen.Condition) *videoLabelDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v videoLabelDo) Select(conds ...field.Expr) *videoLabelDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v videoLabelDo) Where(conds ...gen.Condition) *videoLabelDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v videoLabelDo) Order(conds ...field.Expr) *videoLabelDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v videoLabelDo) Distinct(cols ...field.Expr) *videoLabelDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v videoLabelDo) Omit(cols ...field.Expr) *videoLabelDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v videoLabelDo) Join(table schema.Tabler, on ...field.Expr) *videoLabelDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v videoLabelDo) LeftJoin(table schema.Tabler, on ...field.Expr) *videoLabelDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v videoLabelDo) RightJoin(table schema.Tabler, on ...field.Expr) *videoLabelDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v videoLabelDo) Group(cols ...field.Expr) *videoLabelDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v videoLabelDo) Having(conds ...gen.Condition) *videoLabelDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v videoLabelDo) Limit(limit int) *videoLabelDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v videoLabelDo) Offset(offset int) *videoLabelDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v videoLabelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *videoLabelDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v videoLabelDo) Unscoped() *videoLabelDo {
	return v.withDO(v.DO.Unscoped())
}

func (v videoLabelDo) Create(values ...*model.VideoLabel) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v videoLabelDo) CreateInBatches(values []*model.VideoLabel, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v videoLabelDo) Save(values ...*model.VideoLabel) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v videoLabelDo) First() (*model.VideoLabel, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoLabel), nil
	}
}

func (v videoLabelDo) Take() (*model.VideoLabel, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoLabel), nil
	}
}

func (v videoLabelDo) Last() (*model.VideoLabel, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoLabel), nil
	}
}

func (v videoLabelDo) Find() ([]*model.VideoLabel, error) {
	result, err := v.DO.Find()
	return result.([]*model.VideoLabel), err
}

func (v videoLabelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.VideoLabel, err error) {
	buf := make([]*model.VideoLabel, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v videoLabelDo) FindInBatches(result *[]*model.VideoLabel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v videoLabelDo) Attrs(attrs ...field.AssignExpr) *videoLabelDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v videoLabelDo) Assign(attrs ...field.AssignExpr) *videoLabelDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v videoLabelDo) Joins(fields ...field.RelationField) *videoLabelDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v videoLabelDo) Preload(fields ...field.RelationField) *videoLabelDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v videoLabelDo) FirstOrInit() (*model.VideoLabel, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoLabel), nil
	}
}

func (v videoLabelDo) FirstOrCreate() (*model.VideoLabel, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoLabel), nil
	}
}

func (v videoLabelDo) FindByPage(offset int, limit int) (result []*model.VideoLabel, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v videoLabelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v videoLabelDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v videoLabelDo) Delete(models ...*model.VideoLabel) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *videoLabelDo) withDO(do gen.Dao) *videoLabelDo {
	v.DO = *do.(*gen.DO)
	return v
}
