// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"sfw/biz/dal/model"
)

func newVideoComment(db *gorm.DB, opts ...gen.DOOption) videoComment {
	_videoComment := videoComment{}

	_videoComment.videoCommentDo.UseDB(db, opts...)
	_videoComment.videoCommentDo.UseModel(&model.VideoComment{})

	tableName := _videoComment.videoCommentDo.TableName()
	_videoComment.ALL = field.NewAsterisk(tableName)
	_videoComment.ID = field.NewInt64(tableName, "id")
	_videoComment.UserID = field.NewInt64(tableName, "user_id")
	_videoComment.VideoID = field.NewInt64(tableName, "video_id")
	_videoComment.RootID = field.NewInt64(tableName, "root_id")
	_videoComment.ParentID = field.NewInt64(tableName, "parent_id")
	_videoComment.Content = field.NewString(tableName, "content")
	_videoComment.CreatedAt = field.NewInt64(tableName, "created_at")
	_videoComment.UpdatedAt = field.NewInt64(tableName, "updated_at")
	_videoComment.DeletedAt = field.NewInt64(tableName, "deleted_at")

	_videoComment.fillFieldMap()

	return _videoComment
}

// videoComment 视频评论表
type videoComment struct {
	videoCommentDo videoCommentDo

	ALL       field.Asterisk
	ID        field.Int64  // 评论ID
	UserID    field.Int64  // 用户ID
	VideoID   field.Int64  // 视频ID
	RootID    field.Int64  // 根评论ID
	ParentID  field.Int64  // 父评论ID
	Content   field.String // 评论内容
	CreatedAt field.Int64  // 创建时间
	UpdatedAt field.Int64  // 修改时间
	DeletedAt field.Int64  // 删除时间

	fieldMap map[string]field.Expr
}

func (v videoComment) Table(newTableName string) *videoComment {
	v.videoCommentDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v videoComment) As(alias string) *videoComment {
	v.videoCommentDo.DO = *(v.videoCommentDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *videoComment) updateTableName(table string) *videoComment {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewInt64(table, "id")
	v.UserID = field.NewInt64(table, "user_id")
	v.VideoID = field.NewInt64(table, "video_id")
	v.RootID = field.NewInt64(table, "root_id")
	v.ParentID = field.NewInt64(table, "parent_id")
	v.Content = field.NewString(table, "content")
	v.CreatedAt = field.NewInt64(table, "created_at")
	v.UpdatedAt = field.NewInt64(table, "updated_at")
	v.DeletedAt = field.NewInt64(table, "deleted_at")

	v.fillFieldMap()

	return v
}

func (v *videoComment) WithContext(ctx context.Context) *videoCommentDo {
	return v.videoCommentDo.WithContext(ctx)
}

func (v videoComment) TableName() string { return v.videoCommentDo.TableName() }

func (v videoComment) Alias() string { return v.videoCommentDo.Alias() }

func (v videoComment) Columns(cols ...field.Expr) gen.Columns {
	return v.videoCommentDo.Columns(cols...)
}

func (v *videoComment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *videoComment) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 9)
	v.fieldMap["id"] = v.ID
	v.fieldMap["user_id"] = v.UserID
	v.fieldMap["video_id"] = v.VideoID
	v.fieldMap["root_id"] = v.RootID
	v.fieldMap["parent_id"] = v.ParentID
	v.fieldMap["content"] = v.Content
	v.fieldMap["created_at"] = v.CreatedAt
	v.fieldMap["updated_at"] = v.UpdatedAt
	v.fieldMap["deleted_at"] = v.DeletedAt
}

func (v videoComment) clone(db *gorm.DB) videoComment {
	v.videoCommentDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v videoComment) replaceDB(db *gorm.DB) videoComment {
	v.videoCommentDo.ReplaceDB(db)
	return v
}

type videoCommentDo struct{ gen.DO }

func (v videoCommentDo) Debug() *videoCommentDo {
	return v.withDO(v.DO.Debug())
}

func (v videoCommentDo) WithContext(ctx context.Context) *videoCommentDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v videoCommentDo) ReadDB() *videoCommentDo {
	return v.Clauses(dbresolver.Read)
}

func (v videoCommentDo) WriteDB() *videoCommentDo {
	return v.Clauses(dbresolver.Write)
}

func (v videoCommentDo) Session(config *gorm.Session) *videoCommentDo {
	return v.withDO(v.DO.Session(config))
}

func (v videoCommentDo) Clauses(conds ...clause.Expression) *videoCommentDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v videoCommentDo) Returning(value interface{}, columns ...string) *videoCommentDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v videoCommentDo) Not(conds ...gen.Condition) *videoCommentDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v videoCommentDo) Or(conds ...gen.Condition) *videoCommentDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v videoCommentDo) Select(conds ...field.Expr) *videoCommentDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v videoCommentDo) Where(conds ...gen.Condition) *videoCommentDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v videoCommentDo) Order(conds ...field.Expr) *videoCommentDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v videoCommentDo) Distinct(cols ...field.Expr) *videoCommentDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v videoCommentDo) Omit(cols ...field.Expr) *videoCommentDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v videoCommentDo) Join(table schema.Tabler, on ...field.Expr) *videoCommentDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v videoCommentDo) LeftJoin(table schema.Tabler, on ...field.Expr) *videoCommentDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v videoCommentDo) RightJoin(table schema.Tabler, on ...field.Expr) *videoCommentDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v videoCommentDo) Group(cols ...field.Expr) *videoCommentDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v videoCommentDo) Having(conds ...gen.Condition) *videoCommentDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v videoCommentDo) Limit(limit int) *videoCommentDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v videoCommentDo) Offset(offset int) *videoCommentDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v videoCommentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *videoCommentDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v videoCommentDo) Unscoped() *videoCommentDo {
	return v.withDO(v.DO.Unscoped())
}

func (v videoCommentDo) Create(values ...*model.VideoComment) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v videoCommentDo) CreateInBatches(values []*model.VideoComment, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v videoCommentDo) Save(values ...*model.VideoComment) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v videoCommentDo) First() (*model.VideoComment, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoComment), nil
	}
}

func (v videoCommentDo) Take() (*model.VideoComment, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoComment), nil
	}
}

func (v videoCommentDo) Last() (*model.VideoComment, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoComment), nil
	}
}

func (v videoCommentDo) Find() ([]*model.VideoComment, error) {
	result, err := v.DO.Find()
	return result.([]*model.VideoComment), err
}

func (v videoCommentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.VideoComment, err error) {
	buf := make([]*model.VideoComment, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v videoCommentDo) FindInBatches(result *[]*model.VideoComment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v videoCommentDo) Attrs(attrs ...field.AssignExpr) *videoCommentDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v videoCommentDo) Assign(attrs ...field.AssignExpr) *videoCommentDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v videoCommentDo) Joins(fields ...field.RelationField) *videoCommentDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v videoCommentDo) Preload(fields ...field.RelationField) *videoCommentDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v videoCommentDo) FirstOrInit() (*model.VideoComment, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoComment), nil
	}
}

func (v videoCommentDo) FirstOrCreate() (*model.VideoComment, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoComment), nil
	}
}

func (v videoCommentDo) FindByPage(offset int, limit int) (result []*model.VideoComment, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v videoCommentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v videoCommentDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v videoCommentDo) Delete(models ...*model.VideoComment) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *videoCommentDo) withDO(do gen.Dao) *videoCommentDo {
	v.DO = *do.(*gen.DO)
	return v
}
