// Code generated by hertz generator.

package interact

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	interact "sfw/biz/model/api/interact"
)

// InteractLikeActionMethod .
// @router /api/v1/interact/like [POST]
func InteractLikeActionMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interact.InteractLikeActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(interact.InteractLikeActionResp)

	c.JSON(consts.StatusOK, resp)
}

// InteractLikeListMethod .
// @router /api/v1/interact/like/list [GET]
func InteractLikeListMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interact.InteractLikeListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(interact.InteractLikeListResp)

	c.JSON(consts.StatusOK, resp)
}

// InteractCommentPublishMethod .
// @router /api/v1/interact/comment/publish [POST]
func InteractCommentPublishMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interact.InteractCommentPublishReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(interact.InteractCommentPublishResp)

	c.JSON(consts.StatusOK, resp)
}

// InteractCommentListMethod .
// @router /api/v1/interact/comment/list [GET]
func InteractCommentListMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interact.InteractCommentListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(interact.InteractCommentListResp)

	c.JSON(consts.StatusOK, resp)
}

// InteractMessageSendMethod .
// @router /api/v1/interact/message/send [POST]
func InteractMessageSendMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interact.InteractMessageSendReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(interact.InteractMessageSendResp)

	c.JSON(consts.StatusOK, resp)
}
