// Code generated by hertz generator.

package tool

import (
	auth "sfw/biz/router/api/api_auth"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return auth.AdminAuth()
}

func _toolMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _admintooldeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tool0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tooldeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _toolgetimageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tooluploadimageMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userrefreshMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _admintooldeleteactivityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _admintooldeletecommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _admintooldeletevideoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _delete0Mw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _tooldeleteactivityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tooldeletecommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tooldeletevideoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tooltokenrefreshMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _refresh_tokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _toolrefreshtokenrefreshMw() []app.HandlerFunc {
	// your code...
	return nil
}
