// Code generated by hertz generator.

package tool

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _toolMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _admintooldeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tool0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tooldeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _toolgetimageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tooluploadimageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userrefreshMw() []app.HandlerFunc {
	// your code...
	return nil
}
