// Code generated by hertz generator.

package activity

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _activityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _activityfeedmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _activityinfomethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _activitylistmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _activitypublishmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}
