// Code generated by hertz generator.

package interact

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interactMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interactlikeactionmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interactlikelistmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interactcommentlistmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interactcommentpublishmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _messageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interactmessagesendmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}
