// Code generated by hertz generator.

package interact

import (
	auth "sfw/biz/router/api/api_auth"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interactMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interactlikeactionmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interactlikelistmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interactcommentlistmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interactcommentpublishmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _messageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interactmessagesendmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _activityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interactlikeactivityactionmethodMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _comment0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interactionlikecommentactionmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interactlikevideoactionmethodMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _interactlikevideolistmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interactlikecommentactionmethodMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _interactcommentactivitypublishmethodMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _interactcommentvideopublishmethodMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _activity0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _video0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interactcommentactivitylistmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interactcommentvideolistmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _child_commentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interactactivitychildcommentlistmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _activity1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _video1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _child_comment0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interactvideochildcommentlistmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interactvideodislikemethodMw() []app.HandlerFunc {
	// your code...
	return nil
}
