// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameActivityImage = "ActivityImages"

// ActivityImage 图片表
type ActivityImage struct {
	ImageID    int64 `gorm:"column:image_id;primaryKey;comment:图片ID" json:"image_id"`       // 图片ID
	ActivityID int64 `gorm:"column:activity_id;primaryKey;comment:动态ID" json:"activity_id"` // 动态ID
	CreatedAt  int64 `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`     // 创建时间
	DeletedAt  int64 `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`              // 删除时间
}

// TableName ActivityImage's table name
func (*ActivityImage) TableName() string {
	return TableNameActivityImage
}
