// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameActivityComment = "ActivityComment"

// ActivityComment 动态评论表
type ActivityComment struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:评论ID" json:"id"` // 评论ID
	UserID     int64  `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`            // 用户ID
	ActivityID int64  `gorm:"column:activity_id;not null;comment:动态ID" json:"activity_id"`    // 动态ID
	ParentID   int64  `gorm:"column:parent_id;not null;comment:父评论ID" json:"parent_id"`       // 父评论ID
	RootID     int64  `gorm:"column:root_id;not null;comment:根评论ID" json:"root_id"`           // 根评论ID
	Content    string `gorm:"column:content;not null;comment:评论内容" json:"content"`            // 评论内容
	CreatedAt  int64  `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`      // 创建时间
	UpdatedAt  int64  `gorm:"column:updated_at;not null;comment:修改时间" json:"updated_at"`      // 修改时间
	DeletedAt  int64  `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`               // 删除时间
}

// TableName ActivityComment's table name
func (*ActivityComment) TableName() string {
	return TableNameActivityComment
}
