// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameActivityCommentLike = "ActivityCommentLike"

// ActivityCommentLike 动态评论点赞表
type ActivityCommentLike struct {
	UserID    int64 `gorm:"column:user_id;primaryKey;comment:用户ID" json:"user_id"`         // 用户ID
	CommentID int64 `gorm:"column:comment_id;primaryKey;comment:动态评论ID" json:"comment_id"` // 动态评论ID
	CreatedAt int64 `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`     // 创建时间
	DeletedAt int64 `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`              // 删除时间
}

// TableName ActivityCommentLike's table name
func (*ActivityCommentLike) TableName() string {
	return TableNameActivityCommentLike
}
