// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameActivityLike = "ActivityLike"

// ActivityLike 动态点赞表
type ActivityLike struct {
	UserID     int64 `gorm:"column:user_id;primaryKey;comment:用户ID" json:"user_id"`         // 用户ID
	ActivityID int64 `gorm:"column:activity_id;primaryKey;comment:动态ID" json:"activity_id"` // 动态ID
	CreatedAt  int64 `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`     // 创建时间
	DeletedAt  int64 `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`              // 删除时间
}

// TableName ActivityLike's table name
func (*ActivityLike) TableName() string {
	return TableNameActivityLike
}
