// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameImage = "Image"

// Image 图片表
type Image struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:图片ID" json:"id"` // 图片ID
	UserID    int64  `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`            // 用户ID
	ImageURL  string `gorm:"column:image_url;not null;comment:图片url" json:"image_url"`       // 图片url
	CreatedAt int64  `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`      // 创建时间
	DeletedAt int64  `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`               // 删除时间
}

// TableName Image's table name
func (*Image) TableName() string {
	return TableNameImage
}
