// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMessage = "Message"

// Message 消息表
type Message struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:消息ID" json:"id"` // 消息ID
	FromUserID int64  `gorm:"column:from_user_id;not null;comment:发送者ID" json:"from_user_id"` // 发送者ID
	ToUserID   int64  `gorm:"column:to_user_id;not null;comment:接受者ID" json:"to_user_id"`     // 接受者ID
	Content    string `gorm:"column:content;not null;comment:内容" json:"content"`              // 内容
	CreatedAt  int64  `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`      // 创建时间
	DeletedAt  int64  `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`               // 删除时间
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
