// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameReview = "Review"

// Review 视频审核表
type Review struct {
	ID           int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:审核ID" json:"id"`  // 审核ID
	VideoID      int64  `gorm:"column:video_id;not null;comment:视频ID" json:"video_id"`           // 视频ID
	ReviewerID   int64  `gorm:"column:reviewer_id;not null;comment:审核者ID" json:"reviewer_id"`    // 审核者ID
	SubmittedAt  int64  `gorm:"column:submitted_at;not null;comment:提交时间" json:"submitted_at"`   // 提交时间
	ReviewedAt   int64  `gorm:"column:reviewed_at;not null;comment:审核时间" json:"reviewed_at"`     // 审核时间
	ReviewResult string `gorm:"column:review_result;not null;comment:审核结果" json:"review_result"` // 审核结果
}

// TableName Review's table name
func (*Review) TableName() string {
	return TableNameReview
}
