// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "User"

// User 用户表
type User struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:用户ID" json:"id"` // 用户ID
	Username  string `gorm:"column:username;not null;comment:用户名称" json:"username"`          // 用户名称
	Password  string `gorm:"column:password;not null;comment:用户密码" json:"password"`          // 用户密码
	Email     string `gorm:"column:email;not null;comment:用户邮箱" json:"email"`                // 用户邮箱
	Role      string `gorm:"column:role;not null;comment:权限" json:"role"`                    // 权限
	AvatarURL string `gorm:"column:avatar_url;comment:用户头像url" json:"avatar_url"`            // 用户头像url
	CreatedAt int64  `gorm:"column:created_at;not null;comment:创建账号时间" json:"created_at"`    // 创建账号时间
	UpdatedAt int64  `gorm:"column:updated_at;not null;comment:最近登录时间" json:"updated_at"`    // 最近登录时间
	DeletedAt int64  `gorm:"column:deleted_at;comment:账号删除时间" json:"deleted_at"`             // 账号删除时间
	MfaSecret string `gorm:"column:mfa_secret;comment:mfa秘钥" json:"mfa_secret"`              // mfa秘钥
	MfaEnable bool   `gorm:"column:mfa_enable;not null;comment:是否使用mfa" json:"mfa_enable"`   // 是否使用mfa
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
