// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVideoTag = "VideoTag"

// VideoTag 视频标签关联表
type VideoTag struct {
	VideoID   int64 `gorm:"column:video_id;primaryKey;comment:视频ID" json:"video_id"`   // 视频ID
	TagID     int64 `gorm:"column:tag_id;primaryKey;comment:标签ID" json:"tag_id"`       // 标签ID
	CreatedAt int64 `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"` // 创建时间
	DeletedAt int64 `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`          // 删除时间
}

// TableName VideoTag's table name
func (*VideoTag) TableName() string {
	return TableNameVideoTag
}
