// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVideoLike = "VideoLike"

// VideoLike 视频点赞表
type VideoLike struct {
	UserID    int64 `gorm:"column:user_id;primaryKey;comment:用户ID" json:"user_id"`     // 用户ID
	VideoID   int64 `gorm:"column:video_id;primaryKey;comment:视频ID" json:"video_id"`   // 视频ID
	CreatedAt int64 `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"` // 创建时间
	DeletedAt int64 `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`          // 删除时间
}

// TableName VideoLike's table name
func (*VideoLike) TableName() string {
	return TableNameVideoLike
}
