// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVideo = "Video"

// Video 视频表
type Video struct {
	ID          int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:视频ID" json:"id"` // 视频ID
	UserID      int64  `gorm:"column:user_id;not null;comment:作者ID" json:"user_id"`            // 作者ID
	VideoURL    string `gorm:"column:video_url;not null;comment:视频url" json:"video_url"`       // 视频url
	CoverURL    string `gorm:"column:cover_url;not null;comment:封面url" json:"cover_url"`       // 封面url
	Title       string `gorm:"column:title;not null;comment:标题" json:"title"`                  // 标题
	Description string `gorm:"column:description;not null;comment:简介" json:"description"`      // 简介
	VisitCount  int64  `gorm:"column:visit_count;not null;comment:浏览量" json:"visit_count"`     // 浏览量
	CreatedAt   int64  `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`      // 创建时间
	UpdatedAt   int64  `gorm:"column:updated_at;not null;comment:修改时间" json:"updated_at"`      // 修改时间
	DeletedAt   int64  `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`               // 删除时间
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
