// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	api_activity "sfw/biz/router/api/activity"
	api_interact "sfw/biz/router/api/interact"
	api_oss "sfw/biz/router/api/oss"
	api_relation "sfw/biz/router/api/relation"
	api_report "sfw/biz/router/api/report"
	api_tool "sfw/biz/router/api/tool"
	api_user "sfw/biz/router/api/user"
	api_video "sfw/biz/router/api/video"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	api_interact.Register(r)

	api_oss.Register(r)

	api_report.Register(r)

	api_tool.Register(r)

	api_activity.Register(r)

	api_relation.Register(r)

	api_video.Register(r)

	api_user.Register(r)

}
